name: my-first-workflow
on: push
jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
     - name: printing date from ubuntu
     - run: date
  macos:
    runs-on: macos-latest
    steps:
     - name: printing date from macos
     - run: date
  windows:
    runs-on: windows-latest
    steps:
     - name: printing date from windows
     - run: date
  depends:
   runs-on: macos-latest
   needs: [ubuntu, windows]
   steps:
    - name: printing date from macos
    - run: date
      
