name: my-first-workflow
on: push
jobs:
  job1:
    name: first-job
    uses: actions/checkout@v3 
  job2:
    name: second-job
    runs-on: ubuntu-latest
    steps: 
      - name: running on ubuntu server
        run: echo 'you are a good guy ! |
            pwd
            who am i
            ls -ld
      
